sudo: required
services:
    -   docker

before_install:
    -   docker build -t kailaselamkar/springboot-freemarker -f Dockerfile.dev
    
script:
    docker run kailaselamkar/springboot-freemarker gradle test